language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

addons:
  sonarcloud:
    organization: sartography

install:
  - pip install -r requirements.txt
  - pip install celery
  - pip install coveralls

script:
  - cd tests/SpiffWorkflow
  - coverage run --source=SpiffWorkflow -m unittest discover -v . "*Test.py"
  - coverage xml -i
  - cd ../..

jobs:
  include:
    - stage: coveralls
      script: coveralls
      python: 3.9
    - stage: sonar
      script: sonar-scanner
      python: 3.9
